# Generated by Django 3.2 on 2022-01-13 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='uploads/user/avatar/%Y/%m/%d/')),
                ('monthly_budget', models.PositiveIntegerField(default=2000)),
                ('days_per_week', models.PositiveSmallIntegerField(default=1)),
                ('hours_per_day', models.PositiveSmallIntegerField(default=10)),
                ('vacation_per_year', models.PositiveSmallIntegerField(default=4)),
                ('value_hour', models.PositiveSmallIntegerField(default=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('daily_hours', models.PositiveSmallIntegerField(default=1)),
                ('total_hours', models.PositiveSmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobscalc.profile')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
