# Generated by Django 3.2 on 2022-01-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobscalc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
