# Generated by Django 3.2 on 2022-01-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobscalc', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='value_hour',
        ),
    ]
